version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"  # ホスト8081番 → コンテナ内8081番
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: alertdb
    ports:
      - "3306:3306"

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./data-input:/usr/share/nginx/html/data-input:ro
