CREATE TABLE IF NOT EXISTS value_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    value FLOAT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO value_table (value) VALUES (50.0); -- 初期値
